#!/usr/bin/env bash
# Usage: script/release
# Build the package, tag a commit, and push it to origin

set -e

version="$(script/package | grep Version: | awk '{print $2}')"
[ -n "$version" ] || exit 1

echo $version
git commit --allow-empty -a -m "Release $version"
git tag "v$version"
git push origin
git push origin "v$version"
